services:
  db:
    ports:
      - "5432:5432"

  minio:
    ports:
      - "9000:9000"
      - "9001:9001"

  meilisearch:
    ports:
      - "7700:7700"

  backend:
    volumes:
      - .:/app
    environment:
      MODE: dev
    user: root

  worker:
    volumes:
      - .:/app
    user: root
