[pytest]
testpaths = tests

pythonpath = .

asyncio_mode = auto

env_files =
    .env.test

markers =
    unit: Mark tests as unit tests.
    integration: Mark tests as integration tests.
    e2e: Mark tests as end-to-end tests.