server {

    server_name market.sievers.kz;

    location / {
        default_type text/plain;
        return 200 "Sievers Market — coming soon\n";
    }

    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/market.sievers.kz/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/market.sievers.kz/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}


server {
    if ($host = market.sievers.kz) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    listen [::]:80;

    server_name market.sievers.kz;
    return 404; # managed by Certbot


}
