server {
    server_name sievers.kz www.sievers.kz;

    location / {
        default_type text/plain;
        return 200 "Sievers Market - coming soon\n";
    }

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/sievers.kz/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/sievers.kz/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = sievers.kz) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    listen [::]:80;
    server_name sievers.kz www.sievers.kz;
    return 404; # managed by Certbot


}
