"""add_search_index

Revision ID: 0c5470b4c577
Revises: 93fb6b93e48e
Create Date: 2025-12-20 10:35:06.666976

"""
import os
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c5470b4c577'
down_revision: Union[str, Sequence[str], None] = '93fb6b93e48e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")

    connection_url = op.get_bind().engine.url
    database_name = connection_url.database

    if database_name:
        op.execute(f'ALTER DATABASE "{database_name}" SET pg_trgm.similarity_threshold = 0.03;')
    else:
        raise Exception("Не удалось определить имя базы данных для миграции!")

    op.add_column('listings', sa.Column('search_content', sa.Text(), nullable=True))
    op.add_column(
        'listings',
        sa.Column(
            'search_vector',
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('russian', coalesce(search_content, ''))",
                persisted=True
            ),
            nullable=False
        )
    )

    op.create_index(
        'idx_listings_vector',
        'listings',
        ['search_vector'],
        postgresql_using='gin'
    )

    # Индекс для триграмм (GIST + операторы)
    op.execute("CREATE INDEX idx_listings_trgm ON listings USING gist (search_content gist_trgm_ops);")
    # ### end Alembic commands ###


def downgrade() -> None:
    # Удаляем индексы перед удалением колонок
    op.drop_index('idx_listings_vector', table_name='listings')
    op.execute("DROP INDEX IF EXISTS idx_listings_trgm;")

    op.drop_column('listings', 'search_vector')
    op.drop_column('listings', 'search_content')
