"""add_source_field_to_attributes

Revision ID: 22ec47077ab7
Revises: 5131876a2bf4
Create Date: 2026-07-31 19:36:28.960179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22ec47077ab7'
down_revision: Union[str, Sequence[str], None] = '5131876a2bf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attribute_definitions', sa.Column('source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attribute_definitions', 'source')
    # ### end Alembic commands ###
