"""remove_is_main_field

Revision ID: 82338d5babda
Revises: e28d12e41896
Create Date: 2025-12-09 22:39:42.408679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82338d5babda'
down_revision: Union[str, Sequence[str], None] = 'e28d12e41896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listing_media_listing_position'), table_name='listing_media')
    op.drop_index(op.f('uq_listing_media_one_main'), table_name='listing_media', postgresql_where='(is_main = true)')
    op.create_unique_constraint('uq_listing_media_position', 'listing_media', ['listing_id', 'position'])
    op.drop_column('listing_media', 'is_main')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing_media', sa.Column('is_main', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_constraint('uq_listing_media_position', 'listing_media', type_='unique')
    op.create_index(op.f('uq_listing_media_one_main'), 'listing_media', ['listing_id'], unique=True, postgresql_where='(is_main = true)')
    op.create_index(op.f('ix_listing_media_listing_position'), 'listing_media', ['listing_id', 'position'], unique=False)
    # ### end Alembic commands ###
