"""add password_reset_token in tokentypeenum

Revision ID: 8c5819796a58
Revises: 50d86a5093d6
Create Date: 2025-09-27 11:19:30.393267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c5819796a58'
down_revision: Union[str, Sequence[str], None] = '50d86a5093d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE tokentypeenum ADD VALUE 'PASSWORD_RESET_TOKEN'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
