"""add_is_filterable_flag_for_m2m_table

Revision ID: 93fb6b93e48e
Revises: dbc522065569
Create Date: 2025-12-15 23:35:03.454176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93fb6b93e48e'
down_revision: Union[str, Sequence[str], None] = 'dbc522065569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machinery_subcategory_specification', sa.Column('is_filterable', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machinery_subcategory_specification', 'is_filterable')
    # ### end Alembic commands ###
