"""initial_listings_schema

Revision ID: 95fd2b657672
Revises: 52884e90bb8e
Create Date: 2025-11-23 21:17:03.017443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95fd2b657672'
down_revision: Union[str, Sequence[str], None] = '52884e90bb8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colors',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('hex', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('machinery_manufacturer_countries',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('machinery_manufacturers',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('machinery_specification_groups',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('regions',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roubrics',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit_of_measure',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listings',
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('roubric_id', sa.UUID(), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('currency', sa.Enum('KZT', 'USD', 'EUR', 'RUB', name='listingcurrencyenum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'INACTIVE', 'ARCHIVED', name='listingstatusenum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['roubric_id'], ['roubrics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_listings_author', 'listings', ['author_id'], unique=False)
    op.create_index('ix_listings_region', 'listings', ['region_id'], unique=False)
    op.create_index('ix_listings_roubric', 'listings', ['roubric_id'], unique=False)
    op.create_index('ix_listings_status', 'listings', ['status'], unique=False)
    op.create_table('machinery_categories',
    sa.Column('roubric_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['roubric_id'], ['roubrics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listing_media',
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('media_url', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.Enum('JPEG', 'PNG', 'WEBP', name='mimetypeenum'), nullable=False),
    sa.Column('is_main', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_listing_media_listing_id', 'listing_media', ['listing_id'], unique=False)
    op.create_index('ix_listing_media_listing_position', 'listing_media', ['listing_id', 'position'], unique=False)
    op.create_index('uq_listing_media_one_main', 'listing_media', ['listing_id'], unique=True, postgresql_where=sa.text('is_main = true'))
    op.create_table('machinery_subcategories',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['machinery_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('machinery',
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('subcategory_id', sa.UUID(), nullable=False),
    sa.Column('manufacturer_id', sa.UUID(), nullable=False),
    sa.Column('manufacturer_country_id', sa.UUID(), nullable=False),
    sa.Column('color_id', sa.UUID(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('year_of_issue', sa.Integer(), nullable=False),
    sa.Column('condition', sa.Enum('USED', 'NEW', name='machineryconditionenum'), nullable=False),
    sa.Column('extra_specs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manufacturer_country_id'], ['machinery_manufacturer_countries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['machinery_manufacturers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['machinery_subcategories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_machinery_extra_specs_gin', 'machinery', ['extra_specs'], unique=False, postgresql_using='gin')
    op.create_table('machinery_specifications',
    sa.Column('subcategory_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('value_type', sa.Enum('STRING', 'INTEGER', 'BOOLEAN', 'FLOAT', 'ENUM', name='machineryspecsvaluetypeenum'), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=True),
    sa.Column('is_required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['machinery_specification_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['machinery_subcategories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['unit_of_measure.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subcategory_id', 'key', name='uq_subcategory_key')
    )
    op.create_index('ix_machinery_spec_group', 'machinery_specifications', ['group_id'], unique=False)
    op.create_index('ix_machinery_spec_subcategory', 'machinery_specifications', ['subcategory_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_machinery_spec_subcategory', table_name='machinery_specifications')
    op.drop_index('ix_machinery_spec_group', table_name='machinery_specifications')
    op.drop_table('machinery_specifications')
    op.drop_index('ix_machinery_extra_specs_gin', table_name='machinery', postgresql_using='gin')
    op.drop_table('machinery')
    op.drop_table('machinery_subcategories')
    op.drop_index('uq_listing_media_one_main', table_name='listing_media', postgresql_where=sa.text('is_main = true'))
    op.drop_index('ix_listing_media_listing_position', table_name='listing_media')
    op.drop_index('ix_listing_media_listing_id', table_name='listing_media')
    op.drop_table('listing_media')
    op.drop_table('machinery_categories')
    op.drop_index('ix_listings_status', table_name='listings')
    op.drop_index('ix_listings_roubric', table_name='listings')
    op.drop_index('ix_listings_region', table_name='listings')
    op.drop_index('ix_listings_author', table_name='listings')
    op.drop_table('listings')
    op.drop_table('unit_of_measure')
    op.drop_table('roubrics')
    op.drop_table('regions')
    op.drop_table('machinery_specification_groups')
    op.drop_table('machinery_manufacturers')
    op.drop_table('machinery_manufacturer_countries')
    op.drop_table('colors')
    # ### end Alembic commands ###
