"""set_nullable_for_listing_and_machinery_table_fields

Revision ID: 9e2a5674f518
Revises: 82338d5babda
Create Date: 2025-12-14 00:16:41.385672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e2a5674f518'
down_revision: Union[str, Sequence[str], None] = '82338d5babda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('listing_media', 'media_url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('listing_media', 'mime_type',
               existing_type=postgresql.ENUM('JPEG', 'PNG', 'WEBP', name='mimetypeenum'),
               nullable=True)
    op.alter_column('listing_media', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('listings', 'region_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('listings', 'title',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('listings', 'price',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('listings', 'currency',
               existing_type=postgresql.ENUM('KZT', 'USD', 'EUR', 'RUB', name='listingcurrencyenum'),
               nullable=True)
    op.alter_column('machinery', 'manufacturer_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('machinery', 'manufacturer_country_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('machinery', 'model',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('machinery', 'year_of_issue',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('machinery', 'condition',
               existing_type=postgresql.ENUM('USED', 'NEW', name='machineryconditionenum'),
               nullable=True)
    op.alter_column('machinery', 'extra_specs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('machinery', 'extra_specs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('machinery', 'condition',
               existing_type=postgresql.ENUM('USED', 'NEW', name='machineryconditionenum'),
               nullable=False)
    op.alter_column('machinery', 'year_of_issue',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('machinery', 'model',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('machinery', 'manufacturer_country_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('machinery', 'manufacturer_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('listings', 'currency',
               existing_type=postgresql.ENUM('KZT', 'USD', 'EUR', 'RUB', name='listingcurrencyenum'),
               nullable=False)
    op.alter_column('listings', 'price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('listings', 'title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('listings', 'region_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('listing_media', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('listing_media', 'mime_type',
               existing_type=postgresql.ENUM('JPEG', 'PNG', 'WEBP', name='mimetypeenum'),
               nullable=False)
    op.alter_column('listing_media', 'media_url',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
