"""initial_machinery

Revision ID: a993c64bb5aa
Revises: fbd3a7f81bef
Create Date: 2026-05-06 22:43:37.231581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a993c64bb5aa'
down_revision: Union[str, Sequence[str], None] = 'fbd3a7f81bef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machinery',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('subcategory_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('price', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.Enum('KZT', 'RUB', 'USD', 'EUR', name='pricecurrency', native_enum=False), nullable=True),
    sa.Column('city_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('year_of_issue', sa.Integer(), nullable=True),
    sa.Column('condition', sa.Enum('new', 'used', name='machinerycondition', native_enum=False), nullable=True),
    sa.Column('color_id', sa.UUID(), nullable=True),
    sa.Column('country_id', sa.UUID(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'archived', 'draft', 'deleted', name='listingstatus', native_enum=False), nullable=False),
    sa.Column('engine_power', sa.Integer(), sa.Computed("(attributes->>'engine_power')::integer", persisted=True), nullable=True),
    sa.Column('weight', sa.Integer(), sa.Computed("(attributes->>'weight')::integer", persisted=True), nullable=True),
    sa.Column('length', sa.Integer(), sa.Computed("(attributes->>'length')::integer", persisted=True), nullable=True),
    sa.Column('width', sa.Integer(), sa.Computed("(attributes->>'width')::integer", persisted=True), nullable=True),
    sa.Column('height', sa.Integer(), sa.Computed("(attributes->>'height')::integer", persisted=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_machinery_attributes_gin', 'machinery', ['attributes'], unique=False, postgresql_using='gin')
    op.create_index('ix_machinery_engine_power', 'machinery', ['engine_power'], unique=False)
    op.create_index('ix_machinery_height', 'machinery', ['height'], unique=False)
    op.create_index('ix_machinery_length', 'machinery', ['length'], unique=False)
    op.create_index('ix_machinery_weight', 'machinery', ['weight'], unique=False)
    op.create_index('ix_machinery_width', 'machinery', ['width'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_machinery_width', table_name='machinery')
    op.drop_index('ix_machinery_weight', table_name='machinery')
    op.drop_index('ix_machinery_length', table_name='machinery')
    op.drop_index('ix_machinery_height', table_name='machinery')
    op.drop_index('ix_machinery_engine_power', table_name='machinery')
    op.drop_index('ix_machinery_attributes_gin', table_name='machinery', postgresql_using='gin')
    op.drop_table('machinery')
    # ### end Alembic commands ###
