"""initial_seller

Revision ID: d9bc7b8d479b
Revises: e4e45e59e0a7
Create Date: 2026-01-17 23:35:22.689564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9bc7b8d479b'
down_revision: Union[str, Sequence[str], None] = 'e4e45e59e0a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sellers',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('patronymic', sa.String(length=50), nullable=True),
    sa.Column('seller_type', sa.Enum('ie', 'llp', 'farm', name='sellertype', native_enum=False), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('legal_address', sa.String(length=255), nullable=False),
    sa.Column('tax_id', sa.String(length=12), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('logotype_url', sa.Text(), server_default='default_logotype.png', nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_index(op.f('ix_sellers_tax_id'), 'sellers', ['tax_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sellers_tax_id'), table_name='sellers')
    op.drop_table('sellers')
    # ### end Alembic commands ###
