"""add_delete_enum_value

Revision ID: dbc522065569
Revises: 9e2a5674f518
Create Date: 2025-12-14 03:38:58.177036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbc522065569'
down_revision: Union[str, Sequence[str], None] = '9e2a5674f518'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(
        """
            CREATE TYPE listingstatusenum_new AS ENUM (
                'active', 'inactive', 'draft', 'archived', 'deleted'
            )
        """
    )

    op.execute(
        """
            ALTER TABLE listings
            ALTER COLUMN status TYPE listingstatusenum_new
            USING LOWER(status::text)::listingstatusenum_new
        """
    )

    op.execute("DROP TYPE listingstatusenum")
    op.execute("ALTER TYPE listingstatusenum_new RENAME TO listingstatusenum")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
            CREATE TYPE listingstatusenum_old AS ENUM(
                'ACTIVE', 'INACTIVE', 'DRAFT', 'ARCHIVED'
            )
        """
    )

    op.execute(
        """
            ALTER TABLE listings
            ALTER COLUMN status TYPE listingstatusenum_old
            USING UPPER(status::text)::listingstatusenum_old
        """
    )

    op.execute("DROP TYPE listingstatusenum")
    op.execute("ALTER TYPE listingstatusenum_old RENAME TO listingstatusenum")
    # ### end Alembic commands ###
