"""add_m2m_subs_specs_unit_table

Revision ID: e28d12e41896
Revises: 95fd2b657672
Create Date: 2025-11-27 00:37:08.513457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e28d12e41896'
down_revision: Union[str, Sequence[str], None] = '95fd2b657672'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machinery_subcategory_specification',
    sa.Column('subcategory_id', sa.UUID(), nullable=False),
    sa.Column('specification_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=True),
    sa.Column('is_required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['specification_id'], ['machinery_specifications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['machinery_subcategories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['unit_of_measure.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subcategory_id', 'specification_id', 'unit_id', name='uq_subcategory_spec_unit')
    )
    op.drop_index(op.f('ix_machinery_spec_group'), table_name='machinery_specifications')
    op.drop_index(op.f('ix_machinery_spec_subcategory'), table_name='machinery_specifications')
    op.drop_constraint(op.f('uq_subcategory_key'), 'machinery_specifications', type_='unique')
    op.drop_constraint(op.f('machinery_specifications_subcategory_id_fkey'), 'machinery_specifications', type_='foreignkey')
    op.drop_constraint(op.f('machinery_specifications_unit_id_fkey'), 'machinery_specifications', type_='foreignkey')
    op.drop_column('machinery_specifications', 'is_required')
    op.drop_column('machinery_specifications', 'unit_id')
    op.drop_column('machinery_specifications', 'subcategory_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machinery_specifications', sa.Column('subcategory_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('machinery_specifications', sa.Column('unit_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('machinery_specifications', sa.Column('is_required', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('machinery_specifications_unit_id_fkey'), 'machinery_specifications', 'unit_of_measure', ['unit_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('machinery_specifications_subcategory_id_fkey'), 'machinery_specifications', 'machinery_subcategories', ['subcategory_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_subcategory_key'), 'machinery_specifications', ['subcategory_id', 'key'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_machinery_spec_subcategory'), 'machinery_specifications', ['subcategory_id'], unique=False)
    op.create_index(op.f('ix_machinery_spec_group'), 'machinery_specifications', ['group_id'], unique=False)
    op.drop_table('machinery_subcategory_specification')
    # ### end Alembic commands ###
